// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/node_agent/v1/node_agent.proto

package nodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_DEFAULT     CommandType = 0
	CommandType_COMMAND_TYPE_CUSTOM      CommandType = 1
	CommandType_COMMAND_TYPE_INSTALL_APP CommandType = 2
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_DEFAULT",
		1: "COMMAND_TYPE_CUSTOM",
		2: "COMMAND_TYPE_INSTALL_APP",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_DEFAULT":     0,
		"COMMAND_TYPE_CUSTOM":      1,
		"COMMAND_TYPE_INSTALL_APP": 2,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_agent_v1_node_agent_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_node_agent_v1_node_agent_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{0}
}

type JobStatus int32

const (
	JobStatus_JOB_STATUS_RUNNING   JobStatus = 0
	JobStatus_JOB_STATUS_COMPLETED JobStatus = 1
	JobStatus_JOB_STATUS_FAILED    JobStatus = 2
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_RUNNING",
		1: "JOB_STATUS_COMPLETED",
		2: "JOB_STATUS_FAILED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_RUNNING":   0,
		"JOB_STATUS_COMPLETED": 1,
		"JOB_STATUS_FAILED":    2,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_agent_v1_node_agent_proto_enumTypes[1].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_proto_node_agent_v1_node_agent_proto_enumTypes[1]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{1}
}

type RegisterCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // validated against the auth token server-side
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          CommandType            `protobuf:"varint,4,opt,name=type,proto3,enum=node_agent.v1.CommandType" json:"type,omitempty"`
	ScriptPath    string                 `protobuf:"bytes,5,opt,name=script_path,json=scriptPath,proto3" json:"script_path,omitempty"` // only set for COMMAND_TYPE_CUSTOM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCommandRequest) Reset() {
	*x = RegisterCommandRequest{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCommandRequest) ProtoMessage() {}

func (x *RegisterCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCommandRequest.ProtoReflect.Descriptor instead.
func (*RegisterCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterCommandRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterCommandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterCommandRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterCommandRequest) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_DEFAULT
}

func (x *RegisterCommandRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

type RegisterCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registered    int32                  `protobuf:"varint,1,opt,name=registered,proto3" json:"registered,omitempty"` // total commands upserted in this batch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCommandsResponse) Reset() {
	*x = RegisterCommandsResponse{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCommandsResponse) ProtoMessage() {}

func (x *RegisterCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCommandsResponse.ProtoReflect.Descriptor instead.
func (*RegisterCommandsResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterCommandsResponse) GetRegistered() int32 {
	if x != nil {
		return x.Registered
	}
	return 0
}

type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NodeMessage_JobResult
	//	*NodeMessage_Heartbeat
	//	*NodeMessage_LogEntry
	//	*NodeMessage_Metric
	//	*NodeMessage_HealthResult
	Payload       isNodeMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{2}
}

func (x *NodeMessage) GetPayload() isNodeMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NodeMessage) GetJobResult() *JobResultPayload {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_JobResult); ok {
			return x.JobResult
		}
	}
	return nil
}

func (x *NodeMessage) GetHeartbeat() *HeartbeatPayload {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *NodeMessage) GetLogEntry() *LogEntryPayload {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_LogEntry); ok {
			return x.LogEntry
		}
	}
	return nil
}

func (x *NodeMessage) GetMetric() *MetricPayload {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Metric); ok {
			return x.Metric
		}
	}
	return nil
}

func (x *NodeMessage) GetHealthResult() *HealthCheckResultPayload {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_HealthResult); ok {
			return x.HealthResult
		}
	}
	return nil
}

type isNodeMessage_Payload interface {
	isNodeMessage_Payload()
}

type NodeMessage_JobResult struct {
	JobResult *JobResultPayload `protobuf:"bytes,1,opt,name=job_result,json=jobResult,proto3,oneof"`
}

type NodeMessage_Heartbeat struct {
	Heartbeat *HeartbeatPayload `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type NodeMessage_LogEntry struct {
	LogEntry *LogEntryPayload `protobuf:"bytes,3,opt,name=log_entry,json=logEntry,proto3,oneof"`
}

type NodeMessage_Metric struct {
	Metric *MetricPayload `protobuf:"bytes,4,opt,name=metric,proto3,oneof"`
}

type NodeMessage_HealthResult struct {
	HealthResult *HealthCheckResultPayload `protobuf:"bytes,5,opt,name=health_result,json=healthResult,proto3,oneof"`
}

func (*NodeMessage_JobResult) isNodeMessage_Payload() {}

func (*NodeMessage_Heartbeat) isNodeMessage_Payload() {}

func (*NodeMessage_LogEntry) isNodeMessage_Payload() {}

func (*NodeMessage_Metric) isNodeMessage_Payload() {}

func (*NodeMessage_HealthResult) isNodeMessage_Payload() {}

type MetricPayload struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent    float32                `protobuf:"fixed32,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	RamTotalBytes      uint64                 `protobuf:"varint,2,opt,name=ram_total_bytes,json=ramTotalBytes,proto3" json:"ram_total_bytes,omitempty"`
	RamUsedBytes       uint64                 `protobuf:"varint,3,opt,name=ram_used_bytes,json=ramUsedBytes,proto3" json:"ram_used_bytes,omitempty"`
	RamAvailableBytes  uint64                 `protobuf:"varint,4,opt,name=ram_available_bytes,json=ramAvailableBytes,proto3" json:"ram_available_bytes,omitempty"`
	RamUsagePercent    float32                `protobuf:"fixed32,5,opt,name=ram_usage_percent,json=ramUsagePercent,proto3" json:"ram_usage_percent,omitempty"`
	DiskTotalBytes     uint64                 `protobuf:"varint,6,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	DiskUsedBytes      uint64                 `protobuf:"varint,7,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskAvailableBytes uint64                 `protobuf:"varint,8,opt,name=disk_available_bytes,json=diskAvailableBytes,proto3" json:"disk_available_bytes,omitempty"`
	DiskUsagePercent   float32                `protobuf:"fixed32,9,opt,name=disk_usage_percent,json=diskUsagePercent,proto3" json:"disk_usage_percent,omitempty"`
	UptimeSeconds      int64                  `protobuf:"varint,10,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetricPayload) Reset() {
	*x = MetricPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPayload) ProtoMessage() {}

func (x *MetricPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPayload.ProtoReflect.Descriptor instead.
func (*MetricPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{3}
}

func (x *MetricPayload) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *MetricPayload) GetRamTotalBytes() uint64 {
	if x != nil {
		return x.RamTotalBytes
	}
	return 0
}

func (x *MetricPayload) GetRamUsedBytes() uint64 {
	if x != nil {
		return x.RamUsedBytes
	}
	return 0
}

func (x *MetricPayload) GetRamAvailableBytes() uint64 {
	if x != nil {
		return x.RamAvailableBytes
	}
	return 0
}

func (x *MetricPayload) GetRamUsagePercent() float32 {
	if x != nil {
		return x.RamUsagePercent
	}
	return 0
}

func (x *MetricPayload) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *MetricPayload) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *MetricPayload) GetDiskAvailableBytes() uint64 {
	if x != nil {
		return x.DiskAvailableBytes
	}
	return 0
}

func (x *MetricPayload) GetDiskUsagePercent() float32 {
	if x != nil {
		return x.DiskUsagePercent
	}
	return 0
}

func (x *MetricPayload) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_ExecuteJob
	//	*ServerMessage_StreamLogs
	//	*ServerMessage_StopLogs
	//	*ServerMessage_ConfigureHealthCheck
	//	*ServerMessage_StopHealthCheck
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetExecuteJob() *ExecuteJobPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ExecuteJob); ok {
			return x.ExecuteJob
		}
	}
	return nil
}

func (x *ServerMessage) GetStreamLogs() *StreamLogsPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_StreamLogs); ok {
			return x.StreamLogs
		}
	}
	return nil
}

func (x *ServerMessage) GetStopLogs() *StopLogsPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_StopLogs); ok {
			return x.StopLogs
		}
	}
	return nil
}

func (x *ServerMessage) GetConfigureHealthCheck() *ConfigureHealthCheckPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ConfigureHealthCheck); ok {
			return x.ConfigureHealthCheck
		}
	}
	return nil
}

func (x *ServerMessage) GetStopHealthCheck() *StopHealthCheckPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_StopHealthCheck); ok {
			return x.StopHealthCheck
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_ExecuteJob struct {
	ExecuteJob *ExecuteJobPayload `protobuf:"bytes,1,opt,name=execute_job,json=executeJob,proto3,oneof"`
}

type ServerMessage_StreamLogs struct {
	StreamLogs *StreamLogsPayload `protobuf:"bytes,2,opt,name=stream_logs,json=streamLogs,proto3,oneof"`
}

type ServerMessage_StopLogs struct {
	StopLogs *StopLogsPayload `protobuf:"bytes,3,opt,name=stop_logs,json=stopLogs,proto3,oneof"`
}

type ServerMessage_ConfigureHealthCheck struct {
	ConfigureHealthCheck *ConfigureHealthCheckPayload `protobuf:"bytes,4,opt,name=configure_health_check,json=configureHealthCheck,proto3,oneof"`
}

type ServerMessage_StopHealthCheck struct {
	StopHealthCheck *StopHealthCheckPayload `protobuf:"bytes,5,opt,name=stop_health_check,json=stopHealthCheck,proto3,oneof"`
}

func (*ServerMessage_ExecuteJob) isServerMessage_Payload() {}

func (*ServerMessage_StreamLogs) isServerMessage_Payload() {}

func (*ServerMessage_StopLogs) isServerMessage_Payload() {}

func (*ServerMessage_ConfigureHealthCheck) isServerMessage_Payload() {}

func (*ServerMessage_StopHealthCheck) isServerMessage_Payload() {}

type JobResultPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=node_agent.v1.JobStatus" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResultPayload) Reset() {
	*x = JobResultPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResultPayload) ProtoMessage() {}

func (x *JobResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResultPayload.ProtoReflect.Descriptor instead.
func (*JobResultPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{5}
}

func (x *JobResultPayload) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResultPayload) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_RUNNING
}

func (x *JobResultPayload) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *JobResultPayload) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HeartbeatPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPayload) Reset() {
	*x = HeartbeatPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPayload) ProtoMessage() {}

func (x *HeartbeatPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPayload.ProtoReflect.Descriptor instead.
func (*HeartbeatPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatPayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ExecuteJobPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CommandName   string                 `protobuf:"bytes,2,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	CommandType   CommandType            `protobuf:"varint,3,opt,name=command_type,json=commandType,proto3,enum=node_agent.v1.CommandType" json:"command_type,omitempty"`
	Params        string                 `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"` // JSON-encoded parameters (e.g. for INSTALL_APP)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteJobPayload) Reset() {
	*x = ExecuteJobPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteJobPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJobPayload) ProtoMessage() {}

func (x *ExecuteJobPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJobPayload.ProtoReflect.Descriptor instead.
func (*ExecuteJobPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteJobPayload) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ExecuteJobPayload) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *ExecuteJobPayload) GetCommandType() CommandType {
	if x != nil {
		return x.CommandType
	}
	return CommandType_COMMAND_TYPE_DEFAULT
}

func (x *ExecuteJobPayload) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

// Sent by server to ask the agent to start streaming logs.
type StreamLogsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`    // systemd unit name, e.g. "autohost-agent" or "" for all
	Lines         int32                  `protobuf:"varint,2,opt,name=lines,proto3" json:"lines,omitempty"` // how many historical lines to tail first (0 = no history)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsPayload) Reset() {
	*x = StreamLogsPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsPayload) ProtoMessage() {}

func (x *StreamLogsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsPayload.ProtoReflect.Descriptor instead.
func (*StreamLogsPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{8}
}

func (x *StreamLogsPayload) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *StreamLogsPayload) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

// Sent by server to ask the agent to stop streaming logs.
type StopLogsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopLogsPayload) Reset() {
	*x = StopLogsPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopLogsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopLogsPayload) ProtoMessage() {}

func (x *StopLogsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopLogsPayload.ProtoReflect.Descriptor instead.
func (*StopLogsPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{9}
}

// Sent by agent to the server, one per log line.
type LogEntryPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampUs   int64                  `protobuf:"varint,1,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"` // Unix microseconds
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`                                   // source systemd unit
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntryPayload) Reset() {
	*x = LogEntryPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryPayload) ProtoMessage() {}

func (x *LogEntryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryPayload.ProtoReflect.Descriptor instead.
func (*LogEntryPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{10}
}

func (x *LogEntryPayload) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *LogEntryPayload) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *LogEntryPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Sent by the server to configure or update a health check on the agent.
type ConfigureHealthCheckPayload struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MonitorId          string                 `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	ServiceName        string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	CheckType          string                 `protobuf:"bytes,3,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"` // "process" | "tcp" | "http"
	HttpUrl            string                 `protobuf:"bytes,4,opt,name=http_url,json=httpUrl,proto3" json:"http_url,omitempty"`
	HttpExpectedStatus int32                  `protobuf:"varint,5,opt,name=http_expected_status,json=httpExpectedStatus,proto3" json:"http_expected_status,omitempty"`
	TcpHost            string                 `protobuf:"bytes,6,opt,name=tcp_host,json=tcpHost,proto3" json:"tcp_host,omitempty"`
	TcpPort            int32                  `protobuf:"varint,7,opt,name=tcp_port,json=tcpPort,proto3" json:"tcp_port,omitempty"`
	IntervalSeconds    int32                  `protobuf:"varint,8,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	FailureThreshold   int32                  `protobuf:"varint,9,opt,name=failure_threshold,json=failureThreshold,proto3" json:"failure_threshold,omitempty"`
	Enabled            bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConfigureHealthCheckPayload) Reset() {
	*x = ConfigureHealthCheckPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureHealthCheckPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureHealthCheckPayload) ProtoMessage() {}

func (x *ConfigureHealthCheckPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureHealthCheckPayload.ProtoReflect.Descriptor instead.
func (*ConfigureHealthCheckPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigureHealthCheckPayload) GetMonitorId() string {
	if x != nil {
		return x.MonitorId
	}
	return ""
}

func (x *ConfigureHealthCheckPayload) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ConfigureHealthCheckPayload) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *ConfigureHealthCheckPayload) GetHttpUrl() string {
	if x != nil {
		return x.HttpUrl
	}
	return ""
}

func (x *ConfigureHealthCheckPayload) GetHttpExpectedStatus() int32 {
	if x != nil {
		return x.HttpExpectedStatus
	}
	return 0
}

func (x *ConfigureHealthCheckPayload) GetTcpHost() string {
	if x != nil {
		return x.TcpHost
	}
	return ""
}

func (x *ConfigureHealthCheckPayload) GetTcpPort() int32 {
	if x != nil {
		return x.TcpPort
	}
	return 0
}

func (x *ConfigureHealthCheckPayload) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *ConfigureHealthCheckPayload) GetFailureThreshold() int32 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

func (x *ConfigureHealthCheckPayload) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// Sent by the server to remove a health check from the agent.
type StopHealthCheckPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonitorId     string                 `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopHealthCheckPayload) Reset() {
	*x = StopHealthCheckPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopHealthCheckPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopHealthCheckPayload) ProtoMessage() {}

func (x *StopHealthCheckPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopHealthCheckPayload.ProtoReflect.Descriptor instead.
func (*StopHealthCheckPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{12}
}

func (x *StopHealthCheckPayload) GetMonitorId() string {
	if x != nil {
		return x.MonitorId
	}
	return ""
}

// Sent by the agent after each health check execution.
type HealthCheckResultPayload struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MonitorId           string                 `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "up" | "down"
	LatencyMs           int32                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Message             string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ConsecutiveFailures int32                  `protobuf:"varint,5,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealthCheckResultPayload) Reset() {
	*x = HealthCheckResultPayload{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResultPayload) ProtoMessage() {}

func (x *HealthCheckResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResultPayload.ProtoReflect.Descriptor instead.
func (*HealthCheckResultPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{13}
}

func (x *HealthCheckResultPayload) GetMonitorId() string {
	if x != nil {
		return x.MonitorId
	}
	return ""
}

func (x *HealthCheckResultPayload) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResultPayload) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *HealthCheckResultPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResultPayload) GetConsecutiveFailures() int32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

type MetricRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent    float32                `protobuf:"fixed32,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	RamTotalBytes      uint64                 `protobuf:"varint,2,opt,name=ram_total_bytes,json=ramTotalBytes,proto3" json:"ram_total_bytes,omitempty"`
	RamUsedBytes       uint64                 `protobuf:"varint,3,opt,name=ram_used_bytes,json=ramUsedBytes,proto3" json:"ram_used_bytes,omitempty"`
	RamAvailableBytes  uint64                 `protobuf:"varint,4,opt,name=ram_available_bytes,json=ramAvailableBytes,proto3" json:"ram_available_bytes,omitempty"`
	RamUsagePercent    float32                `protobuf:"fixed32,5,opt,name=ram_usage_percent,json=ramUsagePercent,proto3" json:"ram_usage_percent,omitempty"`
	DiskTotalBytes     uint64                 `protobuf:"varint,6,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	DiskUsedBytes      uint64                 `protobuf:"varint,7,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskAvailableBytes uint64                 `protobuf:"varint,8,opt,name=disk_available_bytes,json=diskAvailableBytes,proto3" json:"disk_available_bytes,omitempty"`
	DiskUsagePercent   float32                `protobuf:"fixed32,9,opt,name=disk_usage_percent,json=diskUsagePercent,proto3" json:"disk_usage_percent,omitempty"`
	UptimeSeconds      int64                  `protobuf:"varint,10,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{14}
}

func (x *MetricRequest) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *MetricRequest) GetRamTotalBytes() uint64 {
	if x != nil {
		return x.RamTotalBytes
	}
	return 0
}

func (x *MetricRequest) GetRamUsedBytes() uint64 {
	if x != nil {
		return x.RamUsedBytes
	}
	return 0
}

func (x *MetricRequest) GetRamAvailableBytes() uint64 {
	if x != nil {
		return x.RamAvailableBytes
	}
	return 0
}

func (x *MetricRequest) GetRamUsagePercent() float32 {
	if x != nil {
		return x.RamUsagePercent
	}
	return 0
}

func (x *MetricRequest) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *MetricRequest) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *MetricRequest) GetDiskAvailableBytes() uint64 {
	if x != nil {
		return x.DiskAvailableBytes
	}
	return 0
}

func (x *MetricRequest) GetDiskUsagePercent() float32 {
	if x != nil {
		return x.DiskUsagePercent
	}
	return 0
}

func (x *MetricRequest) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type MetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricResponse) Reset() {
	*x = MetricResponse{}
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricResponse) ProtoMessage() {}

func (x *MetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_agent_v1_node_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricResponse.ProtoReflect.Descriptor instead.
func (*MetricResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_agent_v1_node_agent_proto_rawDescGZIP(), []int{15}
}

func (x *MetricResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_node_agent_v1_node_agent_proto protoreflect.FileDescriptor

const file_proto_node_agent_v1_node_agent_proto_rawDesc = "" +
	"\n" +
	"$proto/node_agent/v1/node_agent.proto\x12\rnode_agent.v1\"\xb8\x01\n" +
	"\x16RegisterCommandRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12.\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1a.node_agent.v1.CommandTypeR\x04type\x12\x1f\n" +
	"\vscript_path\x18\x05 \x01(\tR\n" +
	"scriptPath\":\n" +
	"\x18RegisterCommandsResponse\x12\x1e\n" +
	"\n" +
	"registered\x18\x01 \x01(\x05R\n" +
	"registered\"\xe2\x02\n" +
	"\vNodeMessage\x12@\n" +
	"\n" +
	"job_result\x18\x01 \x01(\v2\x1f.node_agent.v1.JobResultPayloadH\x00R\tjobResult\x12?\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1f.node_agent.v1.HeartbeatPayloadH\x00R\theartbeat\x12=\n" +
	"\tlog_entry\x18\x03 \x01(\v2\x1e.node_agent.v1.LogEntryPayloadH\x00R\blogEntry\x126\n" +
	"\x06metric\x18\x04 \x01(\v2\x1c.node_agent.v1.MetricPayloadH\x00R\x06metric\x12N\n" +
	"\rhealth_result\x18\x05 \x01(\v2'.node_agent.v1.HealthCheckResultPayloadH\x00R\fhealthResultB\t\n" +
	"\apayload\"\xbe\x03\n" +
	"\rMetricPayload\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x02R\x0fcpuUsagePercent\x12&\n" +
	"\x0fram_total_bytes\x18\x02 \x01(\x04R\rramTotalBytes\x12$\n" +
	"\x0eram_used_bytes\x18\x03 \x01(\x04R\framUsedBytes\x12.\n" +
	"\x13ram_available_bytes\x18\x04 \x01(\x04R\x11ramAvailableBytes\x12*\n" +
	"\x11ram_usage_percent\x18\x05 \x01(\x02R\x0framUsagePercent\x12(\n" +
	"\x10disk_total_bytes\x18\x06 \x01(\x04R\x0ediskTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\a \x01(\x04R\rdiskUsedBytes\x120\n" +
	"\x14disk_available_bytes\x18\b \x01(\x04R\x12diskAvailableBytes\x12,\n" +
	"\x12disk_usage_percent\x18\t \x01(\x02R\x10diskUsagePercent\x12%\n" +
	"\x0euptime_seconds\x18\n" +
	" \x01(\x03R\ruptimeSeconds\"\x9c\x03\n" +
	"\rServerMessage\x12C\n" +
	"\vexecute_job\x18\x01 \x01(\v2 .node_agent.v1.ExecuteJobPayloadH\x00R\n" +
	"executeJob\x12C\n" +
	"\vstream_logs\x18\x02 \x01(\v2 .node_agent.v1.StreamLogsPayloadH\x00R\n" +
	"streamLogs\x12=\n" +
	"\tstop_logs\x18\x03 \x01(\v2\x1e.node_agent.v1.StopLogsPayloadH\x00R\bstopLogs\x12b\n" +
	"\x16configure_health_check\x18\x04 \x01(\v2*.node_agent.v1.ConfigureHealthCheckPayloadH\x00R\x14configureHealthCheck\x12S\n" +
	"\x11stop_health_check\x18\x05 \x01(\v2%.node_agent.v1.StopHealthCheckPayloadH\x00R\x0fstopHealthCheckB\t\n" +
	"\apayload\"\x89\x01\n" +
	"\x10JobResultPayload\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.node_agent.v1.JobStatusR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"+\n" +
	"\x10HeartbeatPayload\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xa4\x01\n" +
	"\x11ExecuteJobPayload\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12!\n" +
	"\fcommand_name\x18\x02 \x01(\tR\vcommandName\x12=\n" +
	"\fcommand_type\x18\x03 \x01(\x0e2\x1a.node_agent.v1.CommandTypeR\vcommandType\x12\x16\n" +
	"\x06params\x18\x04 \x01(\tR\x06params\"=\n" +
	"\x11StreamLogsPayload\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12\x14\n" +
	"\x05lines\x18\x02 \x01(\x05R\x05lines\"\x11\n" +
	"\x0fStopLogsPayload\"b\n" +
	"\x0fLogEntryPayload\x12!\n" +
	"\ftimestamp_us\x18\x01 \x01(\x03R\vtimestampUs\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xf3\x02\n" +
	"\x1bConfigureHealthCheckPayload\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\tR\tmonitorId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"check_type\x18\x03 \x01(\tR\tcheckType\x12\x19\n" +
	"\bhttp_url\x18\x04 \x01(\tR\ahttpUrl\x120\n" +
	"\x14http_expected_status\x18\x05 \x01(\x05R\x12httpExpectedStatus\x12\x19\n" +
	"\btcp_host\x18\x06 \x01(\tR\atcpHost\x12\x19\n" +
	"\btcp_port\x18\a \x01(\x05R\atcpPort\x12)\n" +
	"\x10interval_seconds\x18\b \x01(\x05R\x0fintervalSeconds\x12+\n" +
	"\x11failure_threshold\x18\t \x01(\x05R\x10failureThreshold\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\"7\n" +
	"\x16StopHealthCheckPayload\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\tR\tmonitorId\"\xbd\x01\n" +
	"\x18HealthCheckResultPayload\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\tR\tmonitorId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x05R\tlatencyMs\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x121\n" +
	"\x14consecutive_failures\x18\x05 \x01(\x05R\x13consecutiveFailures\"\xbe\x03\n" +
	"\rMetricRequest\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x02R\x0fcpuUsagePercent\x12&\n" +
	"\x0fram_total_bytes\x18\x02 \x01(\x04R\rramTotalBytes\x12$\n" +
	"\x0eram_used_bytes\x18\x03 \x01(\x04R\framUsedBytes\x12.\n" +
	"\x13ram_available_bytes\x18\x04 \x01(\x04R\x11ramAvailableBytes\x12*\n" +
	"\x11ram_usage_percent\x18\x05 \x01(\x02R\x0framUsagePercent\x12(\n" +
	"\x10disk_total_bytes\x18\x06 \x01(\x04R\x0ediskTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\a \x01(\x04R\rdiskUsedBytes\x120\n" +
	"\x14disk_available_bytes\x18\b \x01(\x04R\x12diskAvailableBytes\x12,\n" +
	"\x12disk_usage_percent\x18\t \x01(\x02R\x10diskUsagePercent\x12%\n" +
	"\x0euptime_seconds\x18\n" +
	" \x01(\x03R\ruptimeSeconds\"*\n" +
	"\x0eMetricResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*^\n" +
	"\vCommandType\x12\x18\n" +
	"\x14COMMAND_TYPE_DEFAULT\x10\x00\x12\x17\n" +
	"\x13COMMAND_TYPE_CUSTOM\x10\x01\x12\x1c\n" +
	"\x18COMMAND_TYPE_INSTALL_APP\x10\x02*T\n" +
	"\tJobStatus\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x00\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x01\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x022\x8f\x02\n" +
	"\x10NodeAgentService\x12d\n" +
	"\x10RegisterCommands\x12%.node_agent.v1.RegisterCommandRequest\x1a'.node_agent.v1.RegisterCommandsResponse(\x01\x12G\n" +
	"\aConnect\x12\x1a.node_agent.v1.NodeMessage\x1a\x1c.node_agent.v1.ServerMessage(\x010\x01\x12L\n" +
	"\rReportMetrics\x12\x1c.node_agent.v1.MetricRequest\x1a\x1d.node_agent.v1.MetricResponseB;Z9github.com/arturo/autohost-cloud-api/internal/grpc/nodepbb\x06proto3"

var (
	file_proto_node_agent_v1_node_agent_proto_rawDescOnce sync.Once
	file_proto_node_agent_v1_node_agent_proto_rawDescData []byte
)

func file_proto_node_agent_v1_node_agent_proto_rawDescGZIP() []byte {
	file_proto_node_agent_v1_node_agent_proto_rawDescOnce.Do(func() {
		file_proto_node_agent_v1_node_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_agent_v1_node_agent_proto_rawDesc), len(file_proto_node_agent_v1_node_agent_proto_rawDesc)))
	})
	return file_proto_node_agent_v1_node_agent_proto_rawDescData
}

var file_proto_node_agent_v1_node_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_node_agent_v1_node_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_node_agent_v1_node_agent_proto_goTypes = []any{
	(CommandType)(0),                    // 0: node_agent.v1.CommandType
	(JobStatus)(0),                      // 1: node_agent.v1.JobStatus
	(*RegisterCommandRequest)(nil),      // 2: node_agent.v1.RegisterCommandRequest
	(*RegisterCommandsResponse)(nil),    // 3: node_agent.v1.RegisterCommandsResponse
	(*NodeMessage)(nil),                 // 4: node_agent.v1.NodeMessage
	(*MetricPayload)(nil),               // 5: node_agent.v1.MetricPayload
	(*ServerMessage)(nil),               // 6: node_agent.v1.ServerMessage
	(*JobResultPayload)(nil),            // 7: node_agent.v1.JobResultPayload
	(*HeartbeatPayload)(nil),            // 8: node_agent.v1.HeartbeatPayload
	(*ExecuteJobPayload)(nil),           // 9: node_agent.v1.ExecuteJobPayload
	(*StreamLogsPayload)(nil),           // 10: node_agent.v1.StreamLogsPayload
	(*StopLogsPayload)(nil),             // 11: node_agent.v1.StopLogsPayload
	(*LogEntryPayload)(nil),             // 12: node_agent.v1.LogEntryPayload
	(*ConfigureHealthCheckPayload)(nil), // 13: node_agent.v1.ConfigureHealthCheckPayload
	(*StopHealthCheckPayload)(nil),      // 14: node_agent.v1.StopHealthCheckPayload
	(*HealthCheckResultPayload)(nil),    // 15: node_agent.v1.HealthCheckResultPayload
	(*MetricRequest)(nil),               // 16: node_agent.v1.MetricRequest
	(*MetricResponse)(nil),              // 17: node_agent.v1.MetricResponse
}
var file_proto_node_agent_v1_node_agent_proto_depIdxs = []int32{
	0,  // 0: node_agent.v1.RegisterCommandRequest.type:type_name -> node_agent.v1.CommandType
	7,  // 1: node_agent.v1.NodeMessage.job_result:type_name -> node_agent.v1.JobResultPayload
	8,  // 2: node_agent.v1.NodeMessage.heartbeat:type_name -> node_agent.v1.HeartbeatPayload
	12, // 3: node_agent.v1.NodeMessage.log_entry:type_name -> node_agent.v1.LogEntryPayload
	5,  // 4: node_agent.v1.NodeMessage.metric:type_name -> node_agent.v1.MetricPayload
	15, // 5: node_agent.v1.NodeMessage.health_result:type_name -> node_agent.v1.HealthCheckResultPayload
	9,  // 6: node_agent.v1.ServerMessage.execute_job:type_name -> node_agent.v1.ExecuteJobPayload
	10, // 7: node_agent.v1.ServerMessage.stream_logs:type_name -> node_agent.v1.StreamLogsPayload
	11, // 8: node_agent.v1.ServerMessage.stop_logs:type_name -> node_agent.v1.StopLogsPayload
	13, // 9: node_agent.v1.ServerMessage.configure_health_check:type_name -> node_agent.v1.ConfigureHealthCheckPayload
	14, // 10: node_agent.v1.ServerMessage.stop_health_check:type_name -> node_agent.v1.StopHealthCheckPayload
	1,  // 11: node_agent.v1.JobResultPayload.status:type_name -> node_agent.v1.JobStatus
	0,  // 12: node_agent.v1.ExecuteJobPayload.command_type:type_name -> node_agent.v1.CommandType
	2,  // 13: node_agent.v1.NodeAgentService.RegisterCommands:input_type -> node_agent.v1.RegisterCommandRequest
	4,  // 14: node_agent.v1.NodeAgentService.Connect:input_type -> node_agent.v1.NodeMessage
	16, // 15: node_agent.v1.NodeAgentService.ReportMetrics:input_type -> node_agent.v1.MetricRequest
	3,  // 16: node_agent.v1.NodeAgentService.RegisterCommands:output_type -> node_agent.v1.RegisterCommandsResponse
	6,  // 17: node_agent.v1.NodeAgentService.Connect:output_type -> node_agent.v1.ServerMessage
	17, // 18: node_agent.v1.NodeAgentService.ReportMetrics:output_type -> node_agent.v1.MetricResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_node_agent_v1_node_agent_proto_init() }
func file_proto_node_agent_v1_node_agent_proto_init() {
	if File_proto_node_agent_v1_node_agent_proto != nil {
		return
	}
	file_proto_node_agent_v1_node_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*NodeMessage_JobResult)(nil),
		(*NodeMessage_Heartbeat)(nil),
		(*NodeMessage_LogEntry)(nil),
		(*NodeMessage_Metric)(nil),
		(*NodeMessage_HealthResult)(nil),
	}
	file_proto_node_agent_v1_node_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerMessage_ExecuteJob)(nil),
		(*ServerMessage_StreamLogs)(nil),
		(*ServerMessage_StopLogs)(nil),
		(*ServerMessage_ConfigureHealthCheck)(nil),
		(*ServerMessage_StopHealthCheck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_agent_v1_node_agent_proto_rawDesc), len(file_proto_node_agent_v1_node_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_agent_v1_node_agent_proto_goTypes,
		DependencyIndexes: file_proto_node_agent_v1_node_agent_proto_depIdxs,
		EnumInfos:         file_proto_node_agent_v1_node_agent_proto_enumTypes,
		MessageInfos:      file_proto_node_agent_v1_node_agent_proto_msgTypes,
	}.Build()
	File_proto_node_agent_v1_node_agent_proto = out.File
	file_proto_node_agent_v1_node_agent_proto_goTypes = nil
	file_proto_node_agent_v1_node_agent_proto_depIdxs = nil
}
